apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: HemanthKumar
      module: frontend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: HemanthKumar
        module: frontend
    spec:
      containers:
<<<<<<< HEAD
        - name: frontend
          image: hemanthkumar75/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
=======
      - name: frontend
        image: hemanthkumar75/frontend:v1
        imagePullPolicy: Always
        # ports:
        # - containerPort: 80
>>>>>>> a6678e4908a4ab6550bdca917dd6b7ff9b2f2aec
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: frontend
  type: NodePort #LoadBalancer
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
