apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: HemanthKumar
      module: db
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: HemanthKumar
        module: db
    spec:
      containers:
        - name: mysql
          image: hemanthkumar75/mysql:v1
          imagePullPolicy: Always
<<<<<<< HEAD
          ports:
            - containerPort: 3306
=======
          # ports:
          #   - containerPort: 3306
>>>>>>> a6678e4908a4ab6550bdca917dd6b7ff9b2f2aec
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: db
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
